name: Check deps for vulnerabilities

on:
  workflow_call:
  schedule:
    - cron: '0 1 * * 1' # every monday
      timezone: Europe/Amsterdam

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: jomco/clojure-action@v0
      with: { m2-cache-key: m2-nvd }

    - name: Check clojure dependencies with NVD
      run: make nvd
