name: Check deps for vulnerabilities

on:
  workflow_call:
  schedule:
    - cron: '0 1 * * 1' # every monday
      timezone: Europe/Amsterdam

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: jomco/clojure-action@fae8cb45f4bf09bb63cdcbe8277f14d9243bf609 # v0
      with: { m2-cache-key: m2-nvd }

    - name: Check clojure dependencies with NVD
      run: make nvd
