name: Check deps for freshness

on: workflow_call

jobs:
  deps:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v7
    - uses: jomco/clojure-action@v0
      with: { m2-cache-key: m2-nvd }

    - name: Check dependency freshness
      run: make outdated
