name: Run checks, tests and docker build

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with: { path: "~/.m2", key: "${{ runner.os }}-m2" }

    - name: Install clj runtime
      run: .github/workflows/install-binaries.sh

    - name: Run linters
      run: bin/clojure -M:lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with: { path: "~/.m2", key: "${{ runner.os }}-m2" }

    - name: Install clj runtime
      run: .github/workflows/install-binaries.sh

    - name: Run tests
      env:
        GATEWAY_ROOT_URL: ${{ secrets.GATEWAY_ROOT_URL }}
        GATEWAY_BASIC_AUTH_USER: ${{ secrets.GATEWAY_BASIC_AUTH_USER }}
        GATEWAY_BASIC_AUTH_PASS: ${{ secrets.GATEWAY_BASIC_AUTH_PASS }}

      run: bin/clojure -M:test
