name: Run checks, tests and docker build

on: push

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with: { path: "~/.m2", key: "${{ runner.os }}-m2" }

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install clj runtime
      run: |
        cd "$HOME"
        curl -L -O https://github.com/clojure/brew-install/releases/latest/download/posix-install.sh
        chmod +x posix-install.sh
        sudo ./posix-install.sh

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 6.2

    - name: Run tests
      env:
        GATEWAY_URL: https://gateway.test.surfeduhub.nl/
        GATEWAY_BASIC_AUTH_USER: ${{ secrets.GATEWAY_BASIC_AUTH_USER }}
        GATEWAY_BASIC_AUTH_PASS: ${{ secrets.GATEWAY_BASIC_AUTH_PASS }}
        SERVER_PORT: 3002

      run: make check
