name: Run checks, tests and docker build

on: workflow_call

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: jomco/clojure-action@fae8cb45f4bf09bb63cdcbe8277f14d9243bf609 # v0
      with: { m2-cache-key: m2-test }

    - name: Start Redis
      uses: supercharge/redis-github-action@1.8.1
      with:
        redis-version: 6.2

    - name: Run tests
      env:
        GATEWAY_URL: https://gateway.test.surfeduhub.nl/
        GATEWAY_BASIC_AUTH_USER: ${{ secrets.GATEWAY_BASIC_AUTH_USER }}
        GATEWAY_BASIC_AUTH_PASS: ${{ secrets.GATEWAY_BASIC_AUTH_PASS }}
        SERVER_PORT: 3002

      run: make check
